### ISSUE TITLE
Quick tool change

### ISSUE THREAD

**Issue by javiavid** [FoxDanger/TWB-2#1]
It is not possible to use that tool if you don't open that panel in davinci first. This forces you that every time you change tools in a different panel you have to press an extra button in the wave panel.

For example, I am using gain on primaries and I want to use red gain on bars.
1-Select modes button
2-Select bars mode (in mapper)
3-Select bars button (for davinci)
4-Select the red gain knob

Having to use step 3 is an unnecessary extra step. In addition to speed, because that way you could create a favorite mode, with the tools you use the most and avoid having to continually change modes and panels.
If you configure that favorites mode well, you can almost work only in that mode and you have the most accessible tools to use them directly, without having to think in which mode and in which panel they are.

In my favorites mode it would be like this:
1-I select knob red gain

It is 3 steps less!

I do not know how what you did to remove the primary pages yesterday is programmed, but this takes away an unnecessary step and you gain speed and versatility, due to the favorites.

When I was referring to what is the closest thing to an original panel (without TWB), it is that with an original panel, if you want to use a tool you don't need to think about how the davinci screen is, you look for your tool on the wave screen and You use it.

Perhaps there is some option that is not possible, but I think that the vast majority can be achieved.

**Comment by FoxDanger** [comment]
Yeah, after do that change of the tabs I thought the same: Why not make every tool force the change directly to the respective tools on davinci.

THat's completely possible, I'm gonna do it as soon as possible.

**Comment by javiavid** [comment]
Great!

**Comment by FoxDanger** [comment]
Done with TWB 2.
