### ISSUE TITLE
Next Node and Prev Node davinci configuration

### ISSUE THREAD

**Issue by javiavid** [FoxDanger/TWB-2#10]
In the davinci keyboard configuration Next Node and Prev Node are not properly assigned.
According to the script it should be Shift+Y and Shift+U.

**Comment by FoxDanger** [comment]
Did you loaded on davinci the Davinci Shortcuts map for TWB?

Inside "mapping" folder there's a list of shortcuts that you need load on Davinci. It's the same of the davinci default shortcuts, but with some new shortcuts for tools and functions that are natively not assigned.

**Comment by javiavid** [comment]
The problem is that the TWB_Davinci_Resolve_Keyboard_Shortcuts.txt file does not have the correct settings. For example, the keyboard shortcut for Next Node is:
nodesNext := Alt+Shift+'

**Comment by FoxDanger** [comment]
Sorry, I didn't export the latest shortcuts list. It was outdated. Already corrected it.,
