### ISSUE TITLE
Lift vs Gain Steps

### ISSUE THREAD

**Issue by javiavid** [FoxDanger/TWB-2#2]
With the same speed setting in Mapper Lift it moves twice as much as Gain.
The minimum step is very large.

The ideal would be to try to reach the original sensitivity, I suppose it is difficult because it is saturated with so many keyboard combinations together, but at least you should try to be able to adjust this.

I leave a video to see the difference and the comparison with the original.

https://drive.google.com/file/d/19t-RXlzduyKehi8a5-Y8KjJp94bFNhZV/view?usp=sharing

**Comment by FoxDanger** [comment]
This has nothing to do with TWB. To the same on davinci without the controller :D

Lift and Gain will always respond differently. It's how it works :D

**Comment by javiavid** [comment]
Perhaps it is difficult, but I think it could be improved.
I upload a sensitivity comparison between Tangent vs mouse vs TWB.

https://drive.google.com/file/d/1YxqVAewW2SiqKh-VKnCLgUucs2kf7ww1/view?usp=sharing
