### ISSUE TITLE
Unify shortcuts

### ISSUE THREAD

**Issue by javiavid** [FoxDanger/TWB-2#3]
I was trying to modify the speed of the Highlights tool, when looking for Highlights in AHK I got Gain / Highlights, it would really be called Gain / Highlight. I know it's a small detail 😄

-In Mapper it is called HL and has the shortcut Ctrl Shift Win N
-In AHK the shortcut is Win Ctrl Shift N
-In the shortcut document that combination is empty and says that it is not used due to problems with windows.

Mapper always uses CTRL SHIFT ALT WIN. I think it would be easy to change in AHK and in the shortcut document with a regex or find and replace, so everything would be unified and it would be easier to do searches in AHK. Since Mapper is fixed, maybe it should be like Mapper.

And from the shortcut document, I understand that it is due to lack of time.

**Comment by FoxDanger** [comment]
Was a hard time do all this work, for sure there's a lot of things that can be organized. I'll do this 👍

**Comment by FoxDanger** [comment]
Done.

**Comment by FoxDanger** [comment]
Better well organized and everything commented and documented on TWB 2.
