### ISSUE TITLE
Timer speed

### ISSUE THREAD

**Issue by javiavid** [FoxDanger/TWB-2#4]
I think it would be nice to increase the timer time a bit. Maybe 600 or 700. Another option if you see that it does not work is to create 2 types of timer ..
When you use a "direct tool" sat, temp, contrast .. it's fine, but when you have to press a button first and then move the jog, sometimes you don't have time and the release happens. I have also detected it when you use a tool slowly, for example hue lift.

**Comment by FoxDanger** [comment]
Yeah, this is possible and I notice that too. I think I'll change it only for the wheels, will be better for sure 👍

**Comment by FoxDanger** [comment]
Done and working way better now with TWB 2.
