### ISSUE TITLE
Add in Lum vs SAT black and white points

### ISSUE THREAD

**Issue by javiavid** [FoxDanger/TWB-2#5]
Sometimes when you correct an image with temp, you manage to correct the overall white balance, but the highlights are tinted. It is very useful to be able to remove color from the Lum Vs Sat curve.

I propose to add 2 more mouse positions, black and white. It would also be good for SAT vs SAT.
![image](https://user-images.githubusercontent.com/7627504/94543925-e9e70900-024a-11eb-90d0-45ed37a08149.png)

Really the interesting thing is how it happens in temp (which changes the page), add here click on the white icon, move to the point of the white and regulate from there. 

![image](https://user-images.githubusercontent.com/7627504/94543605-8e1c8000-024a-11eb-964d-60f9ef94d74d.png)

But maybe this is more specific to each user.

**Comment by FoxDanger** [comment]
Sadly it's not possible now. I had some problem that I don't remember now what was. 

What is maybe possible is do like "curves 1 and 2" and create a object with variables for these two points... But will be like a "fix".

PS: This method of desaturate high and shadows to clean tint is not the best way to do it, in fact is not really good do that. 

Use the the LOG wheels to do this with LR/HR is way better, precise and controlled.

**Comment by javiavid** [comment]
Thanks for the advice, it helps me to see another technique.
I don't usually use LR HR, but I've tried both and I think I like Lum / sat better. I think he has more control with the curve than with HL.
If you look at the waveform and the image, the highlights are cleaner in the curved version.



![image](https://user-images.githubusercontent.com/7627504/94572420-49580f80-0271-11eb-9a96-31d307f0e8b7.png)

**Comment by FoxDanger** [comment]
Done with TWB 2. THere's a way better system for curves and hue curves now.
