### ISSUE TITLE
Curves VS Improvement to knobs

### ISSUE THREAD

**Issue by FoxDanger** [FoxDanger/TWB-2#6]
If we have some spare shortcuts, it's possible to use them to transfer Curves VS from buttons + mouse use to knobs use (output on know left/right and input on alternative know left/right).

This means a lot of shortcuts use, so maybe is not possible. Have to check.

**Comment by javiavid** [comment]
As I mentioned there are many resets, maybe you can get spare shortcuts.

**Comment by FoxDanger** [comment]
Done way better with TWB 2.
