### ISSUE TITLE
Support for multiple monitors

### ISSUE THREAD

**Issue by javiavid** [FoxDanger/TWB-2#9]
I am testing a Dual configuration of davinci and it is not working properly. The mouse always goes to the active monitor and not to the global coordinate.
I have tried to change in AHK Client for Screen in CoordMode, but the same thing happens.

I've tried a simple script like this and it works fine, switching monitors.

CoordMode, Mouse, Screen
MouseMove, 140, 946
Sleep, 500
MouseMove, 2549, 380

**Comment by FoxDanger** [comment]
Done with TWB 2.
